/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EngageRouteImport } from './routes/engage'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InitiativesIndexRouteImport } from './routes/initiatives/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as InitiativesSlugRouteImport } from './routes/initiatives/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageRoute = EngageRouteImport.update({
  id: '/engage',
  path: '/engage',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesIndexRoute = InitiativesIndexRouteImport.update({
  id: '/initiatives/',
  path: '/initiatives/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesSlugRoute = InitiativesSlugRouteImport.update({
  id: '/initiatives/$slug',
  path: '/initiatives/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/engage': typeof EngageRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/engage': typeof EngageRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/initiatives': typeof InitiativesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/engage': typeof EngageRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/engage'
    | '/gallery'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/initiatives/$slug'
    | '/blog/'
    | '/initiatives/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/engage'
    | '/gallery'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/initiatives/$slug'
    | '/blog'
    | '/initiatives'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/engage'
    | '/gallery'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/initiatives/$slug'
    | '/blog/'
    | '/initiatives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EngageRoute: typeof EngageRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  InitiativesSlugRoute: typeof InitiativesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  InitiativesIndexRoute: typeof InitiativesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage': {
      id: '/engage'
      path: '/engage'
      fullPath: '/engage'
      preLoaderRoute: typeof EngageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/': {
      id: '/initiatives/'
      path: '/initiatives'
      fullPath: '/initiatives/'
      preLoaderRoute: typeof InitiativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/$slug': {
      id: '/initiatives/$slug'
      path: '/initiatives/$slug'
      fullPath: '/initiatives/$slug'
      preLoaderRoute: typeof InitiativesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EngageRoute: EngageRoute,
  GalleryRoute: GalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  InitiativesSlugRoute: InitiativesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  InitiativesIndexRoute: InitiativesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
